### ISSUE TITLE
More specific error handling needed?

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabctools#109]
May be completely unrelated but user just reported on discord

```
Traceback (most recent call last):
  File "/app/sabnzbd/downloader.py", line 704, in process_nw_worker
    self.process_nw(read_fds[nw_queue.get()])
  File "/app/sabnzbd/downloader.py", line 714, in process_nw
    bytes_received, done = nw.recv_chunk()
                           ^^^^^^^^^^^^^^^
  File "/app/sabnzbd/newswrapper.py", line 196, in recv_chunk
    bytes_recv = sabctools.unlocked_ssl_recv_into(self.nntp.sock, self.data_view[self.data_position :])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Failed to read data
```

_Originally posted by @thezoggy in https://github.com/sabnzbd/sabnzbd/issues/2752#issuecomment-1863432775_

**Comment by Safihre** [comment]
@mnightingale I created an issue here because I wanted to check with you what to do about this one. We used to just catch all in a bare try/except, which resulted in me missing a bug.

I will admit I'm not sure what kind of problems would get to this code?
https://github.com/sabnzbd/sabctools/blob/65032b832586a79991dd1f9491b94fbd4bf859ae/src/unlocked_ssl.cc#L221-L222
Are these fatal errors that result in closed connections? Then we can raise `PyExc_ConnectionError` which aborts the connection here: https://github.com/sabnzbd/sabnzbd/blob/063a6428f3e5e12b97320ebeb878113ee3480b2d/sabnzbd/downloader.py#L717-L719

**Comment by thezoggy** [comment]
i asked the user that reported this to share logs/more info. so far nothing. but if i get anything i'll pass along here

**Comment by mnightingale** [comment]
I think the normal bits which fill out the error from the SSL state would be [here](https://github.com/python/cpython/blob/14d4c7742a26a3c2253e0a0be476981104b29f5a/Modules/_ssl.c#L2594) and  [here](https://github.com/python/cpython/blob/14d4c7742a26a3c2253e0a0be476981104b29f5a/Modules/_ssl.c#L2611).

But from a cursory glance yes, I think other than a `SSL_ERROR_WANT_READ` you can raise a `PyExc_ConnectionError` regard the socket as corrupt and recreate/reset it.

**Comment by Safihre** [comment]
Decided to go for `PyExc_ConnectionAbortedError` so it's distinguishable from the other exception, in case that's ever needed.
