### ISSUE TITLE
module 'sabctools' has no attribute 'bytearray_malloc'

### ISSUE THREAD

**Issue by msurg** [sabnzbd/sabctools#110]
Hello,
Upgraded to 4.2.1 on Rocky Linux 8.
Python Version: | 3.9.18 (main, Nov 18 2023, 01:00:14)  [GCC 8.5.0 20210514 (Red Hat 8.5.0-20)] [UTF-8]
OpenSSL: | OpenSSL 1.1.1k  FIPS 25 Mar 2021

with
/usr/bin/python3.9 -c "import sabctools; print(sabctools.__version__, sabctools.__file__);"
 get
`8.1.0 /usr/local/lib64/python3.9/site-packages/sabctools/__init__.py`

Now SABnzbd starts but cannot connect to server. When I try to test connection to server I get the following error

`module 'sabctools' has no attribute 'bytearray_malloc'`

Any one can point me to the right direction?

**Comment by Safihre** [comment]
Try to fully remove sabctools by pip uninstall. 
Make sure SABnzbd isn't running.
Then install again.
