### ISSUE TITLE
[6.1.0] Test failure on armhf: OverflowError: Python int too large to convert to C ssize_t

### ISSUE THREAD

**Issue by jcfp** [sabnzbd/sabctools#83]
Build works, tests fail in test_crc32_zero_unpad_expected across all Ubuntu releases and Python versions, on armhf only:
```
I: pybuild base:217: cd /<<PKGBUILDDIR>>/.pybuild/cpython3_3.8_sabctools/build; python3.8 -m pytest tests
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-4.6.9, py-1.8.1, pluggy-0.13.0
rootdir: /<<PKGBUILDDIR>>, inifile: pytest.ini
collected 51 items

tests/test_crc32.py ................F............                        [ 56%]
tests/test_decoder.py .............                                      [ 82%]
tests/test_encoder.py .                                                  [ 84%]
tests/test_unlocked_ssl.py ........                                      [100%]

=================================== FAILURES ===================================
_______ test_crc32_zero_unpad_expected[4294967295-4294967295-4294967295] _______

crc1 = 4294967295, zeroes = 4294967295, expected = 4294967295

    @pytest.mark.parametrize(
        "crc1,zeroes,expected",
        [
            (0, 0, 0),
            (4294967295, 0, 4294967295),
            (4294967295, 4294967295, 4294967295),
            (100, 200, 1523530880),
        ],
    )
    def test_crc32_zero_unpad_expected(crc1, zeroes, expected):
>       assert sabctools.crc32_zero_unpad(crc1, zeroes) == expected
E       OverflowError: Python int too large to convert to C ssize_t

tests/test_crc32.py:47: OverflowError
===================== 1 failed, 50 passed in 1.36 seconds ======================
```

Full build logs by Ubuntu release: [20.04](https://launchpadlibrarian.net/652463868/buildlog_ubuntu-focal-armhf.sabctools_6.1.0-0ubuntu1~jcfp1~20.04_BUILDING.txt.gz) [22.04](https://launchpad.net/~jcfp/+archive/ubuntu/ppa/+build/25605870/+files/buildlog_ubuntu-jammy-armhf.sabctools_6.1.0-0ubuntu1~jcfp1~22.04_BUILDING.txt.gz) [22.10](https://launchpadlibrarian.net/652463865/buildlog_ubuntu-kinetic-armhf.sabctools_6.1.0-0ubuntu1~jcfp1~22.10_BUILDING.txt.gz) [23.04](https://launchpad.net/~jcfp/+archive/ubuntu/ppa/+build/25605880/+files/buildlog_ubuntu-lunar-armhf.sabctools_6.1.0-0ubuntu1~jcfp1~23.04_BUILDING.txt.gz)

**Comment by animetosho** [comment]
I'm guessing the two instances of `Py_ssize_t` in src/crc32.cc should probably be read as 64-bit ints instead.

**Comment by Safihre** [comment]
@animetosho probably very obvious, but what changes are needed?

**Comment by animetosho** [comment]
Try changing the two instances of [Py_ssize_t types](https://github.com/sabnzbd/sabctools/blob/d89b74b8ce1d842f04bfaed659dcd3a85ec5afb7/src/crc32.cc#L26-L28) to `unsigned long long` and replace the `n` in `PyArg_ParseTuple` with `K`.

I'm guessing it fails on armhf (or 32-bit platforms) because size_t is 32-bit instead of 64-bit, so forcing it to 64-bit avoids overflow.

**Comment by Safihre** [comment]
Thanks @animetosho 
@jcfp Pushed as 6.1.1.
